services:

  whoami:
    image: traefik/whoami:latest
    container_name: openresty-whoami
    restart: "no"
    hostname: openresty-whoami
    networks:
      - default
    labels:
      traefik.enable: false

  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    image: oci.guero.org/openresty-loaded:latest
    container_name: openresty
    hostname: openresty
    restart: "no"
    env_file:
      - .env
    depends_on:
      - whoami
    ports:
      - "127.0.0.1:443:443"
    networks:
      - default
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_ldap.conf:/etc/nginx/nginx_ldap.conf:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx/ca-trust:/etc/nginx/ca-trust:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "--silent", "https://localhost:443"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    labels:
      traefik.enable : false
      # traefik.http.routers.openresty.rule: "Host(`test.example.org`)"
      # traefik.http.routers.openresty.entrypoints: "websecure"
      # traefik.http.routers.openresty.tls.certresolver: "myresolver"
      # traefik.http.services.openresty.loadbalancer.server.port: 443

networks:
  default:
    external: false
    # name: traefik-proxy

