version: '3.7'

################################################################################
# Commonly tweaked configuration options
#-------------------------------------------------------------------------------
x-process-variables: &process-variables
  # for running processes as unprivileged user with UID:GID
  PUID : 1000
  PGID : 1000

x-auth-variables: &auth-variables
  # authentication method: encrypted HTTP basic authentication ('true') vs LDAP ('false')
  # vs unauthenticated ('no_authentication')
  NGINX_BASIC_AUTH : 'true'
  # NGINX LDAP (NGINX_BASIC_AUTH=false) can support LDAP, LDAPS, or LDAP+StartTLS.
  #   For StartTLS, set NGINX_LDAP_TLS_STUNNEL=true to issue the StartTLS command
  #   and use stunnel to tunnel the connection.
  NGINX_LDAP_TLS_STUNNEL : 'false'
  # stunnel will require and verify certificates for StartTLS when one or more
  # trusted CA certificate files are placed in the ./nginx/ca-trust directory.
  # For additional security, hostname or IP address checking of the associated
  # CA certificate(s) can be enabled by providing these values.
  NGINX_LDAP_TLS_STUNNEL_CHECK_HOST : ''
  NGINX_LDAP_TLS_STUNNEL_CHECK_IP : ''
  NGINX_LDAP_TLS_STUNNEL_VERIFY_LEVEL : 2
  # Whether or not nginx should use HTTPS. This is almost CERTAINLY what you want.
  # The only case you may want to set this to false is if you're using another
  # reverse proxy in front of NGINX. Even if set to 'false', NGINX will still
  # listen on port 443 (it just won't be encrypted). If you change this, you'll
  # probably want to change "0.0.0.0:443:443" to something like
  # "127.0.0.1:80:443" in the ports section for the nginx-ldap service and
  # change "https://" to "http://" in its healthcheck.
  NGINX_SSL : 'true'

################################################################################

services:

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: "no"
    hostname: whoami

  nginx-ldap:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/mmguero/nginx-ldap:latest
    container_name: nginx-ldap
    hostname: nginx-ldap
    restart: "no"
    environment:
      << : *process-variables
      << : *auth-variables
    depends_on:
      - whoami
    ports:
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_ldap.conf:/etc/nginx/nginx_ldap.conf:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx/ca-trust:/etc/nginx/ca-trust:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "--silent", "https://localhost:443"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
